myName = input("What is you name?: ")
myFood = input("What is your favourite meal?: ")
myMusic = input("What is your favourite music?: ")
myCity = input("Where do you live?: ")
print("Getting to know you!")
print("")
print("You are")
print(myName)
print("You're probabley hungry for ")
print(myFood)
print("and you're definitely getting your groove on to")
print(myMusic)
print("living in the amazing")
print(myCity)

